name: CI_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set CI Environment Variable
        run: echo "CI_ENV=true" >> $GITHUB_ENV

      - name: Check if Swift Toolchain is Installed
        id: check-swift
        run: |
          if swift --version | grep -q "Swift version 6.0.3"; then
            echo "swift_installed=true" >> $GITHUB_ENV
          else
            echo "swift_installed=false" >> $GITHUB_ENV
          fi

      - name: Install Swift Toolchain
        if: env.swift_installed == 'false'
        run: |
          curl -O https://download.swift.org/swift-6.0.3-release/xcode/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-osx.pkg
          sudo installer -pkg swift-6.0.3-RELEASE-osx.pkg -target /
          echo "/Library/Developer/Toolchains/swift-6.0.3-RELEASE.xctoolchain/usr/bin" >> $GITHUB_PATH

      - name: Check Swift Tools Version
        run: swift --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Run tests for iOS
        run: |
          xcodebuild clean build test -scheme DMAction -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'