name: CI_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Swift Toolchain
        run: |
          curl -O https://download.swift.org/swift-6.0-release/xcode/swift-6.0-RELEASE/swift-6.0-RELEASE-osx.pkg
          sudo installer -pkg swift-6.0-RELEASE-osx.pkg -target /
          echo "/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin" >> $GITHUB_PATH

      - name: Check Swift Tools Version
        run: swift --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --enable-test-discovery